function[x,t]=note(frekans,vurus)% genliði frekansý ve vuruþ deðeri verilen notanýn sinüs sinyalini çizdiren fonksiyon
 fs=8192;
 t=0:1/fs:((vurus)-(1/fs)); 
  a=length(t);
A=linspace(0,1.5,((2*a)/8));
B=linspace(1.5,1,(a/8));
C=linspace(1,1,((4*a)/8));
D=linspace(1,0,(a/8));
 zarf=[A B C D];
 x=zarf*sin(2*pi*frekans*t); %verilen bilgiler doðrultusunde sinus sinyali oluþturur
